import {
  Bath,
  Battery,
  Blinds,
  Camera,
  Clapperboard,
  CloudRain,
  CloudSun,
  Cpu,
  Droplets,
  Fan,
  Lamp,
  Lightbulb,
  Lock,
  Moon,
  PartyPopper,
  Plane,
  Scan,
  Shield,
  Sparkles,
  Sun,
  SunDim,
  Sunrise,
  Thermometer,
  User,
  Video,
  Waves,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  bath: Bath,
  battery: Battery,
  blinds: Blinds,
  camera: Camera,
  chandelier: Lamp,
  clapperboard: Clapperboard,
  "cloud-rain": CloudRain,
  "cloud-sun": CloudSun,
  cpu: Cpu,
  droplets: Droplets,
  fan: Fan,
  lamp: Lamp,
  lightbulb: Lightbulb,
  lock: Lock,
  moon: Moon,
  "party-popper": PartyPopper,
  plane: Plane,
  play: Clapperboard,
  robot: Cpu,
  scan: Scan,
  shield: Shield,
  sparkles: Sparkles,
  sun: Sun,
  "sun-dim": SunDim,
  sunrise: Sunrise,
  thermometer: Thermometer,
  user: User,
  video: Video,
  waves: Waves,
  zap: Zap,
};

export function iconOf(key: string): LucideIcon {
  return ICONS[key] ?? Sparkles;
}
